# Generated by Django 3.2.9 on 2022-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('resource', '0002_auto_20220131_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(blank=True, to='topic.Topic'),
        ),
    ]
