# Generated by Django 3.2.9 on 2022-01-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(blank=True, to='topic.Topic'),
        ),
    ]
