# Generated by Django 4.0.2 on 2022-06-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options_rename_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='start_time',
        ),
    ]
