# Generated by Django 2.1.7 on 2019-12-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='project', name='team',),
    ]
