# Generated by Django 2.2.10 on 2020-06-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='resource', name='tag', field=models.CharField(default='Web', max_length=20),),
    ]
