# Generated by Django 3.1.1 on 2020-10-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_auto_20201007_2250"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="title",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="docs",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="description",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="headline_event",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="image",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="info",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="link",
        ),
    ]
