# Generated by Django 3.1.1 on 2020-10-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_auto_20201020_1805"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(default="Human", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(default="Human", max_length=255),
        ),
        migrations.AlterField(
            model_name="resource",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.topic"
            ),
        ),
    ]
