# Generated by Django 3.1.1 on 2020-10-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_auto_20200515_1214"),
        ("resources", "0004_auto_20201020_1902"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="topic",
        ),
        migrations.AddField(
            model_name="resource",
            name="topic",
            field=models.ManyToManyField(blank=True, to="events.Topic"),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
