# Generated by Django 3.1.1 on 2020-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_auto_20201020_1949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(default=""),
        ),
    ]
