# Generated by Django 4.0.2 on 2022-04-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='years',
            field=models.ManyToManyField(related_name='users', to='users.Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.year'),
        ),
    ]
