# Generated by Django 4.0.2 on 2022-04-18 15:45

from django.db import migrations, models
import django.db.models.deletion
import officialWebsite.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.ForeignKey(default=officialWebsite.users.models.Year.get_current_year, on_delete=django.db.models.deletion.CASCADE, to='users.year'),
        ),
    ]
