# Generated by Django 4.0.2 on 2022-04-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models

def make_many_years(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        user.years.add(user.year)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_years_alter_user_year'),
    ]

    operations = [
        migrations.RunPython(make_many_years)
    ]
