# Generated by Django 4.0.2 on 2022-04-23 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_positions(apps, schema_editor):
    # get all the useers
    users = apps.get_model("users", "User").objects.all()
    # create positions
    for user in users:
        # get the first year from the user
        if not user.role:
            continue
        year = user.years.first()
        # create position
        position = apps.get_model("users", "Position").objects.create(user=user, role=user.role, year=year)
        position.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Core', 'Core'), ('Co-Lead', 'Co-Lead'), ('Mentor', 'Mentor')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.year')),
            ],
        ),
        migrations.RunPython(add_positions),
    ]
