# Generated by Django 3.2.9 on 2021-11-13 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_lead',
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ManyToManyField(related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
