# Generated by Django 2.2.10 on 2020-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(null=True, upload_to='podcast_image/'),
        ),
        migrations.AlterField(
            model_name='podcastseries',
            name='logo',
            field=models.ImageField(upload_to='podcast_logo/'),
        ),
    ]
