# Generated by Django 2.2.5 on 2019-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_auto_20191212_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="heads",
            field=models.ManyToManyField(
                blank=True, related_name="heads", to="members.Member"
            ),
        ),
    ]
