# Generated by Django 3.1.1 on 2020-09-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0008_auto_20191224_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="heads",
        ),
    ]
