# Generated by Django 3.2.9 on 2021-12-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='podcast_guest/')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='podcast_logo/')),
                ('hosted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastGuestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('link_type', models.TextField(max_length=255)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcastguest')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('recorded_on', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='podcast_image/')),
                ('link', models.URLField(max_length=255, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcastguest')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcastseries')),
            ],
        ),
    ]
