# Generated by Django 3.2.9 on 2022-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastseries',
            name='logo',
            field=models.ImageField(upload_to='podcast_series_logo/'),
        ),
        migrations.AlterField(
            model_name='podcastseries',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
