# Generated by Django 4.0.2 on 2022-04-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastguestlink',
            name='guest',
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='name',
            field=models.CharField(blank=True, default='Podcast Number <django.db.models.fields.IntegerField>', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podcastguest',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, to='podcast.PodcastGuestLink'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='podcast.podcastguest'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast_image/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='podcasts', to='podcast.podcastseries'),
        ),
        migrations.AlterField(
            model_name='podcastseries',
            name='hosted',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
