# Generated by Django 4.0.2 on 2022-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_remove_podcastguestlink_guest_podcast_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastseries',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
