# Generated by Django 4.0.2 on 2022-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcastseries_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastguest',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
