# Generated by Django 2.1.7 on 2019-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("github_url", models.URLField()),
                ("linkedin_url", models.URLField()),
                ("twitter_url", models.URLField()),
                ("medium_url", models.URLField()),
                ("dev_url", models.URLField()),
                ("image", models.ImageField(blank=True, upload_to="profile-images/")),
            ],
        ),
    ]
