# Generated by Django 3.0 on 2019-12-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191212_1426'),
        ('members', '0002_member_team'),
    ]

    operations = [
        migrations.AlterField(model_name='member', name='team', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),),
    ]
