# Generated by Django 3.0 on 2019-12-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_auto_20191212_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="team",
        ),
    ]
