# Generated by Django 2.2.8 on 2019-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("medium_url", models.URLField(blank=True)),
                ("dev_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="temp-images/")),
            ],
        ),
    ]
