# Generated by Django 2.2.8 on 2019-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_memberregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
