# Generated by Django 2.2.8 on 2019-12-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='profile-images/default.jpeg', upload_to='profile-images/'),
        ),
    ]
