# Generated by Django 3.1.1 on 2020-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_auto_20200202_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[("Lead", "Lead"), ("Core", "Core")], max_length=255
            ),
        ),
    ]
