# Generated by Django 2.2.10 on 2020-09-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200202_1332'),
    ]

    operations = [
        migrations.AlterField(model_name='member', name='role', field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Core', 'Core')], max_length=255),),
    ]
