# Generated by Django 2.2.10 on 2020-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20200911_1627'),
    ]

    operations = [
        migrations.AlterField(model_name='member', name='role', field=models.CharField(choices=[('Lead', 'Lead'), ('Core', 'Core')], max_length=255),),
    ]
