# Generated by Django 3.1.1 on 2020-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_auto_20200914_2115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("Lead", "Lead"), ("Core", "Core"), ("Co-Lead", "Co-Lead")],
                max_length=255,
                null=True,
            ),
        ),
    ]
