# Generated by Django 3.1.1 on 2020-09-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_auto_20200929_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberregistration",
            name="username",
        ),
    ]
