# Generated by Django 2.1.7 on 2019-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile-images/'),
        ),
    ]
