name: Deploy
on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_publish:
    uses: ./.github/workflows/build_push.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decrypt ansible.gpg
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output ansible ansible.gpg
          chmod 400 ansible
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Deploy
        run: |
          ansible-playbook playbooks/redeploy.yml
        env:
          USER: ${{ secrets.USER }}
          DJANGO_API_DOMAIN: ${{ secrets.DJANGO_API_DOMAIN }}
